# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    -   id: cmake-lint
        additional_dependencies: [pyyaml]
        args: [--config=.cmake-lint.yaml]
        types: [cmake]
-   repo: ssh://git@github.com/Software-GCAI/precommit-scripts
    rev: v1.0.1
    hooks:
    -   id: gc-copyright
