# Search for runatime and arch_man path
foreach(path ${CMAKE_PREFIX_PATH})
  if(EXISTS "${path}/lib/graphcore/include/stddef.h")
    set(RUNTIME_PATH ${path})
  endif()
  if(EXISTS "${path}/lib/graphcore/include/arch/gc_tilearch_ipu0.h")
    set(ARCH_MAN_PATH ${path}/lib/graphcore)
  endif()
  if(EXISTS "${path}/lib/graphcore/include/arch/gc_tile_defines.h")
    set(POPLAR_INCLUDE_PATH ${path}/lib/graphcore/include)
  endif()
endforeach(path)
